from easygame import *

pic_background = load_image('resources/background.png')
pic_dom = load_image('resources/dom.png')
pic_init_screen_nocont = load_image('resources/init_screen_nocont.png')
pic_init_screen = load_image('resources/init_screen.png')
pic_instructions = load_image('resources/instructions.png')
pic_lietadlo = load_image('resources/lietadlo.png')
pic_loss = load_image('resources/loss.png')
pic_loss_clone = load_image('resources/loss_clone.png')
pic_mesto = load_image('resources/mesto.png')
pic_riksa_empty = load_image('resources/riksa_empty.png')
pic_riksa_pomaranc = load_image('resources/riksa_pomaranc.png')
pic_riksa_jablko = load_image('resources/riksa_jablko.png')
pic_riksa_kapusta = load_image('resources/riksa_kapusta.png')
pic_sklad = load_image('resources/sklad.png')
pic_van = load_image('resources/van.png')
pic_veziak = load_image('resources/veziak.png')
pic_win = load_image('resources/win.png')
pic_win_fake = load_image('resources/win_fake.png')
pic_win_pro = load_image('resources/win_pro.png')

